baseurl         = "https://vidishajitani.com/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = "vidisha-jitani"
paginate        = 6
#SectionPagesMenu = "main"
canonifyurls    = true

[params]
  title       = ""
  subtitle    = ""
  copyright   = "© 2018"

  cover = "img/bg-blog.jpg"
  description = "Contains post regrading software engineering"
  metaDescription = ""
  googleAnalytics = "UA-120517141-1"
  customCSS = []
  RSSLink = ""

  twitterName = "vidishajitani25"
  fbName = "vidisha.jitani"
  linkedinName = "vidisha-jitani-02422978"


  showSupport = true

  author = "Vidisha"
  authorAvatar = "img/my-pic.jpg"
  authorLocation = "Gurgaon, India"
  authorWebsite = "https://vidishajitani.com"
  authorDescription = "Lead Product Engineer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/post/:slug/"

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 500

[[menu.main]]
  name = "Newsletter"
  url = "subscribe.html"
  weight = 500